### ISSUE TITLE
docker_client() in target.py lack of parameters

### ISSUE THREAD

**Issue by fabregaszy** [lstephen/construi#111]
When I using construi, it throws an error like:

`
Traceback (most recent call last):
  File "/usr/local/bin/construi", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/construi/cli.py", line 26, in main
    Target(config.for_target(target)).invoke(RunContext(config, args.dry_run))
  File "/usr/local/lib/python2.7/site-packages/construi/target.py", line 26, in __init__
    docker_client())
TypeError: docker_client() takes at least 1 argument (0 given)
`
I check the usage of docker_client, it shall take at least when argument (os.environ) for example.
My docker-compose version is 1.8.0

**Comment by lstephen** [comment]
Fixed this in v36, however I'm seeing a new error now that I have to look into.

```
Traceback (most recent call last):
  File "/usr/local/bin/construi", line 9, in <module>
    load_entry_point('construi==36', 'console_scripts', 'construi')()
  File "/Library/Python/2.7/site-packages/construi/cli.py", line 26, in main
    Target(config.for_target(target)).invoke(RunContext(config, args.dry_run))
  File "/Library/Python/2.7/site-packages/construi/target.py", line 67, in invoke
    Target(run_ctx.config.for_target(target)).invoke(run_ctx)
  File "/Library/Python/2.7/site-packages/construi/target.py", line 78, in invoke
    self.run()
  File "/Library/Python/2.7/site-packages/construi/target.py", line 98, in run
    self.cleanup()
  File "/Library/Python/2.7/site-packages/construi/target.py", line 137, in cleanup
    self.project.kill()
  File "/Library/Python/2.7/site-packages/compose/project.py", line 269, in kill
    parallel.parallel_kill(self.containers(service_names), options)
  File "/Library/Python/2.7/site-packages/compose/project.py", line 457, in containers
    containers = self._labeled_containers(stopped, one_off)
  File "/Library/Python/2.7/site-packages/compose/project.py", line 448, in _labeled_containers
    filters={'label': self.labels(one_off=one_off)})])
  File "/Library/Python/2.7/site-packages/docker/api/container.py", line 70, in containers
    res = self._result(self._get(u, params=params), True)
  File "/Library/Python/2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 140, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname '192.168.99.100' doesn't match 'localhost'
```

**Comment by lstephen** [comment]
https://github.com/docker/compose/issues/3365

**Comment by lstephen** [comment]
My error above looks to have been due to boot2docker. I'm upgraded to Docker for Mac and no longer have this issue.
