### ISSUE TITLE
Fail cleanly if image pull fails

### ISSUE THREAD

**Issue by lstephen** [lstephen/construi#52]
Currently we fail with a stack trace that doesn't indicate what's going on

```
Creating image: 'maven:3-jdk-8'...
Pulling repository maven

/Users/lestephen/.rvm/gems/ruby-2.1.2/gems/docker-api-1.21.4/lib/docker/base.rb:16:in `initialize': Must have id, got: {"id"=>nil, :headers=>{}} (Docker::Error::ArgumentError)
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/gems/docker-api-1.21.4/lib/docker/image.rb:117:in `new'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/gems/docker-api-1.21.4/lib/docker/image.rb:117:in `create'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/gems/construi-0.35.2/lib/construi/image.rb:79:in `create'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/gems/construi-0.35.2/lib/construi/image.rb:68:in `from'
        ...
```

**Comment by lstephen** [comment]
Clearing out after python rewrite
