### ISSUE TITLE
Startup issues sometimes

### ISSUE THREAD

**Issue by lstephen** [lstephen/construi#72]
After bundler has been run as part of the build a second attempt to run construi fails.

```
$ construi build
/Users/lestephen/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'construi' (>= 0) among 8 total gem(s) (Gem::LoadError)
        from /Users/lestephen/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
        from /Users/lestephen/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/bin/construi:22:in `<main>'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

The build will work again after deleting the `.bundle` directory.

This could be due to a combination of gems/rvm/ruby/bundler.

```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

$ gem -v
2.2.5

$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ bundler
/Users/lestephen/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'bundler' (>= 0) among 8 total gem(s) (Gem::LoadError)
        from /Users/lestephen/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
        from /Users/lestephen/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/bin/bundler:22:in `<main>'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/lestephen/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

This is with a build container that installs a Ruby EE version.

Best guess this is a conflict between the way that the container version of Ruby/Gem/Bundler etc works and the Host OSX versions work.

**Comment by lstephen** [comment]
Clearing out after python rewrite
